name: Transpile
on:
  push:
    branches:
      - main
jobs:
  transpile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Transpile
        uses: actions/typescript-action@v1
        with:
          args: tsc
      - name: Upload transpiled code
        uses: actions/upload-artifact@v2
        with:
          name: transpiled
          path: dist/
